defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Theme settings
doks:
    baseurl: 'http://www.intelligentexperiences.net'
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: 
            image: logo.png
        nav:
            - item_name: Articles
              item_url: '#'
            - item_name: Projects
              item_url: '#'
            - item_name: About
              item_url: '#'
    footer:
        content:
            logo:
                text: 
                image: logo-footer.png
            copyright: Copyright &copy; 2018. Clint Francis.<br/>I work at Microsoft, but opinions are mine.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/clint_francis'
            - network_name: instagram
              profile_url: 'https://www.instagram.com/isol/'
            - network_name: github
              profile_url: 'https://github.com/ClintFrancis/IntelligentExperiences'
    google_analytics:
        tracking_code: UA-97901876-1 # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: clintfrancis-github-io # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
